In [75]:
import numpy as np
import matplotlib.pyplot as plt
import holoviews as hv
import seaborn as sns
import pickle as pkl
from core import *

In [76]:
background_dir = "./Data/background_yarrays"
virus_dir = "./Data/yarrays"

In [90]:
with open(f"{background_dir}/background_all_y.pkl",'rb') as infile:
    background_yarrays = pkl.load(infile)
with open(f"{virus_dir}/virus_all_y.pkl",'rb') as infile:
    virus_yarrays = pkl.load(infile)

array([[[0.50000012-0.50000001j, 1.00000001-1.00000026j],
        [0.50000012-0.50000001j, 1.00000001-1.00000026j]],

       [[0.50000027+0.50000018j, 1.00000001+1.00000008j],
        [0.50000027+0.50000018j, 1.00000001+1.00000008j]],

       [[0.50000024-0.4999999j , 1.00000001-1.00000012j],
        [0.50000024-0.4999999j , 1.00000001-1.00000012j]],

       [[0.50000022+0.49999976j, 0.99999977+1.00000019j],
        [0.50000022+0.49999976j, 0.99999977+1.00000019j]],

       [[0.50000011-0.49999971j, 0.99999955-1.00000006j],
        [0.50000011-0.49999971j, 0.99999955-1.00000006j]],

       [[0.50000033+0.49999986j, 0.99999946+1.0000001j ],
        [0.50000033+0.49999986j, 0.99999946+1.0000001j ]],

       [[0.50000025-0.49999992j, 0.9999992 -1.00000006j],
        [0.50000025-0.49999992j, 0.9999992 -1.00000006j]],

       [[0.50000001+0.49999991j, 0.9999991 +0.99999994j],
        [0.50000001+0.49999991j, 0.9999991 +0.99999994j]],

       [[0.50000013-0.50000005j, 0.99999888-0.99999999j]

In [78]:
y0 = np.array([[complex(0.5,0.5),complex(1,1)],[complex(0.5,0.5),complex(1,1)]])

all_y = np.zeros((10,20,2,2),dtype="complex128")

for i in range(10):

    def Y(y,t):
        seq = DNA(5)
        alg = Sequence(seq).run()
        y_t = matrix_multiply(y,expm(alg))
        return y_t

    y_array = np.zeros((20,2,2),dtype="complex128")
    y = y0
    for n in range(20):
        y = rkmk_step(Y,y,n)
        y_array[n] = y

    all_y[i-1] = y_array

In [79]:
def matrix_vector_multiply(m,v,vector_type="row"):
    if vector_type == "row":
        return np.array([np.vdot(v,i) for i in m.T])
    elif vector_type == "column":
        return np.array([np.vdot(i,v) for i in m])

def vector_multiply(v1,v2):
    return np.vdot(v1,v2)

In [80]:
def random_complex_vector(n_components=2):
    vals = np.random.rand(n_components,2)
    vector = np.zeros(n_components,dtype="complex128")
    for i in range(n_components):
        vector[i] = complex(vals[i,0],vals[i,1])
    return vector

In [81]:
random_complex_vector()

array([0.86790372+0.92062319j, 0.67220254+0.3856258j ])

In [82]:
all_y[0].shape

(20, 2, 2)

In [178]:
v1 = random_complex_vector()
v2 = v1
vvr = v1
vvc = v1
v1s = []
v2s = []
vvrs = []
vvcs = []
v1

array([0.55885675+0.73597216j, 0.41234033+0.79048654j])

In [179]:
for i in all_y[0]:
    v1 = matrix_vector_multiply(i,v1,"row")
    v1s.append(v1)
    print(v1)

[-0.27763071-1.24882778j -0.55526157-2.49765576j]
[-2.28968813+1.45679543j -4.57937549+2.91359167j]
[ -5.61972487+1.24933894j -11.23945216+2.49867519j]
[ -6.555581  -10.3035966j  -13.11116784-20.60719117j]
[ 5.62201724+25.28877166j 11.24403186+50.5775433j ]
[46.36618233-29.50014017j 92.73237333-59.00027235j]
[113.7994871 -25.29904541j 227.59900147-50.59813766j]
[132.75064933+208.64777172j 265.50133907+417.29571595j]
[-113.84560863 -512.09761231j -227.69150138-1024.19571945j]
[ -938.9148182  +597.37789643j -1877.83070955+1194.75657038j]
[-2304.43835796 +512.30542553j -4608.8806716 +1024.61097599j]
[-2688.19853234-4225.11613244j -5376.40513597-8450.23683034j]
[2305.37389087+10369.97034193j 4610.74731573+20739.96393519j]
[19013.01497858-12096.89255219j 38026.06218949-24193.82115851j]
[46664.85251498-10374.17048292j 93329.81826398-20748.35148759j]
[ 54436.0213034  +85558.51575859j 108872.21071898+171117.2259664j ]
[-46683.72068926-209991.76950096j -93367.43308844-419984.15766289j]
[-385013

In [180]:
for i in all_y[0]:
    v2 = matrix_vector_multiply(i,v2,"column")
    v2s.append(v2)
    print(v2)

[-0.46670385+1.85024125j -0.46670385+1.85024125j]
[2.07530601+3.47541773j 2.07530601+3.47541773j]
[-2.10016727+8.32608608j -2.10016727+8.32608608j]
[9.33887766+15.63938225j 9.33887766+15.63938225j]
[-9.45075241+37.467395j -9.45075241+37.467395j]
[42.02496508+70.37722934j 42.02496508+70.37722934j]
[-42.52838118+168.60331012j -42.52838118+168.60331012j]
[189.1123779+316.69754591j 189.1123779+316.69754591j]
[-191.37768463+758.71494613j -191.37768463+758.71494613j]
[851.00580236+1425.13897563j 851.00580236+1425.13897563j]
[-861.19965198+3414.21669142j -861.19965198+3414.21669142j]
[3829.52553862+6413.12435245j 3829.52553862+6413.12435245j]
[-3875.39685199+15363.97454238j -3875.39685199+15363.97454238j]
[17232.8651613+28859.0531201j 17232.8651613+28859.0531201j]
[-17439.27018142+69137.8700262j -17439.27018142+69137.8700262j]
[77547.87674438+129865.7036394j 77547.87674438+129865.7036394j]
[-78476.68481646+311120.35550787j -78476.68481646+311120.35550787j]
[348965.3989132+584395.60670661j 348

In [181]:
for i in virus_yarrays[2]:
    vvc = matrix_vector_multiply(i,vvc,"column")
    vvcs.append(vvc)
    print(vvc)

[-0.46670419+1.85024138j -0.46670419+1.85024138j]
[2.07530609+3.47541838j 2.07530609+3.47541838j]
[-2.10016763+8.32608643j -2.10016763+8.32608643j]
[9.3388772+15.63937913j 9.3388772+15.63937913j]
[-9.45075252+37.46737422j -9.45075252+37.46737422j]
[42.0249156+70.37716904j 42.0249156+70.37716904j]
[-42.52837822+168.60308908j -42.52837822+168.60308908j]
[189.11205877+316.69710493j 189.11205877+316.69710493j]
[-191.37767571+758.71358683j -191.37767571+758.71358683j]
[851.00415609+1425.13637618j 851.00415609+1425.13637618j]
[-861.1990352+3414.21053155j -861.1990352+3414.21053155j]
[3829.51937136+6413.11346488j 3829.51937136+6413.11346488j]
[-3875.39686593+15363.95154116j -3875.39686593+15363.95154116j]
[17232.84228997+28859.02230006j 17232.84228997+28859.02230006j]
[-17439.28462962+69137.80760039j -17439.28462962+69137.80760039j]
[77547.82265808+129865.67830255j 77547.82265808+129865.67830255j]
[-78476.85612143+311120.31701811j -78476.85612143+311120.31701811j]
[348965.41670568+584395.8098

In [182]:
for i in virus_yarrays[2]:
    vvr = matrix_vector_multiply(i,vvr,"row")
    vvrs.append(vvr)
    print(vvr)

[-0.2776313 -1.24882784j -0.55526166-2.49765592j]
[-2.289689  +1.4567955j  -4.57937663+2.91359045j]
[ -5.61972676+1.24933872j -11.23945001+2.49867919j]
[ -6.55557771-10.30359732j -13.11115795-20.60719116j]
[ 5.62202617+25.28875056j 11.24405289+50.57751497j]
[46.36613354-29.50008138j 92.73233385-59.0001758j ]
[113.79930125-25.29910593j 227.59870934-50.59820761j]
[132.75016854+208.64755677j 265.50071131+417.29532914j]
[-113.84627717 -512.09657969j -227.69195501-1024.19375591j]
[ -938.91410305 +597.37502337j -1877.82880106+1194.75194011j]
[-2304.43378447 +512.30921172j -4608.87052057+1024.61613196j]
[-2688.18459252-4225.11522155j -5376.38033731-8450.23227369j]
[2305.4001999 +10369.95159842j 4610.78502933+20739.92196295j]
[19013.03324482-12096.82937159j 38026.07312834-24193.69328389j]
[46664.79490711-10374.30601818j 93329.67101151-20748.59833023j]
[ 54435.76041272 +85558.68442317j 108871.61923287+171117.47572425j]
[-46684.46269898-209991.73648583j -93368.85038969-419983.70918496j]
[-385014

In [183]:
for i in range(20):
    print(np.abs(v1s[i]),np.abs(v2s[i]), np.abs(vvrs[i]), np.abs(vvcs[i]))

[1.27931608 2.55863239] [1.90819422 1.90819422] [1.27931626 2.55863256] [1.90819443 1.90819443]
[2.71383947 5.42767872] [4.04789123 4.04789123] [2.71384024 5.42767903] [4.04789183 4.04789183]
[ 5.75692239 11.51384656] [8.5868744 8.5868744] [ 5.75692419 11.51384533] [8.58687483 8.58687483]
[12.21227846 24.42455834] [18.21551298 18.21551298] [12.2122773  24.42455302] [18.21551007 18.21551007]
[25.90615853 51.81231647] [38.64094213 38.64094213] [25.90613988 51.81229339] [38.64092202 38.64092202]
[ 54.95526484 109.91053271] [81.96982433 81.96982433] [ 54.95519212 109.91044757] [81.96974718 81.96974718]
[116.5777207  233.15547818] [173.8842701 173.8842701] [116.57755241 233.15520819] [173.88405506 173.88405506]
[247.29866062 494.59748847] [368.86423933 368.86423933] [247.29822117 494.59682513] [368.8636971 368.8636971]
[ 524.59964462 1049.19983394] [782.47925702 782.47925702] [ 524.5987817  1049.19801564] [782.47793682 782.47793682]
[1112.84382865 2225.68898011] [1659.88914555 1659.88914555

In [184]:
for i in range(20):
    print(np.abs(vvrs[i])/np.abs(v1s[i]),np.abs(vvcs[i])/np.abs(v2s[i]))

[1.00000015 1.00000007] [1.00000011 1.00000011]
[1.00000028 1.00000006] [1.00000015 1.00000015]
[1.00000031 0.99999989] [1.00000005 1.00000005]
[0.99999991 0.99999978] [0.99999984 0.99999984]
[0.99999928 0.99999955] [0.99999948 0.99999948]
[0.99999868 0.99999923] [0.99999906 0.99999906]
[0.99999856 0.99999884] [0.99999876 0.99999876]
[0.99999822 0.99999866] [0.99999853 0.99999853]
[0.99999836 0.99999827] [0.99999831 0.99999831]
[0.99999807 0.99999816] [0.99999815 0.99999815]
[0.99999846 0.99999814] [0.99999826 0.99999826]
[0.99999835 0.99999829] [0.99999833 0.99999833]
[0.99999882 0.99999846] [0.99999859 0.99999859]
[0.99999918 0.99999868] [0.99999886 0.99999886]
[0.99999944 0.99999906] [0.9999992 0.9999992]
[1.00000002 0.99999947] [0.99999967 0.99999967]
[1.0000006 0.9999997] [1.00000001 1.00000001]
[1.0000007  1.00000003] [1.00000027 1.00000027]
[1.00000141 1.00000032] [1.0000007 1.0000007]
[1.00000128 1.00000067] [1.00000089 1.00000089]


In [185]:
for i in range(20):
    print(np.abs(vvrs[i])-np.abs(v1s[i]),np.abs(vvcs[i])-np.abs(v2s[i]))

[1.86846573e-07 1.77532863e-07] [2.12565372e-07 2.12565372e-07]
[7.70557429e-07 3.07393803e-07] [6.02555549e-07 6.02555549e-07]
[ 1.80399527e-06 -1.23057800e-06] [4.26394235e-07 4.26394235e-07]
[-1.15444543e-06 -5.31408680e-06] [-2.91636283e-06 -2.91636283e-06]
[-1.86491631e-05 -2.30845280e-05] [-2.01137915e-05 -2.01137915e-05]
[-7.27222998e-05 -8.51432675e-05] [-7.71405676e-05 -7.71405676e-05]
[-0.00016829 -0.00026998] [-0.00021504 -0.00021504]
[-0.00043945 -0.00066334] [-0.00054223 -0.00054223]
[-0.00086292 -0.00181829] [-0.0013202 -0.0013202]
[-0.00214564 -0.00409575] [-0.00307585 -0.00307585]
[-0.00364283 -0.00879019] [-0.00612365 -0.00612365]
[-0.00825144 -0.01715646] [-0.01250968 -0.01250968]
[-0.01258733 -0.03278754] [-0.02229926 -0.02229926]
[-0.01850407 -0.05941417] [-0.03818717 -0.03818717]
[-0.02682168 -0.0901745 ] [-0.05699618 -0.05699618]
[ 0.0022571  -0.10678816] [-0.049483 -0.049483]
[ 0.1287995 -0.1302136] [0.00457673 0.00457673]
[0.32001856 0.02667733] [0.18357432 0.18

In [186]:
for i in range(20):
    print(np.angle(v1s[i]),np.angle(v2s[i]), np.angle(vvrs[i]), np.angle(vvcs[i]))

[-1.78955182 -1.78955186] [1.8178816 1.8178816] [-1.78955226 -1.78955188] [1.81788176 1.81788176]
[2.57495012 2.57494992] [1.03248347 1.03248347] [2.57495027 2.57495022] [1.03248353 1.03248353]
[2.92283703 2.9228373 ] [1.81788158 1.81788158] [2.92283713 2.92283692] [1.81788161 1.81788161]
[-2.13743897 -2.13743922] [1.03248351 1.03248351] [-2.13743871 -2.13743887] [1.03248344 1.03248344]
[1.35204108 1.35204113] [1.81788153 1.81788153] [1.35204057 1.35204062] [1.81788166 1.81788166]
[-0.56664306 -0.56664296] [1.0324834 1.0324834] [-0.56664263 -0.56664241] [1.03248354 1.03248354]
[-0.21875495 -0.21875512] [1.81788145 1.81788145] [-0.2187558  -0.21875568] [1.81788175 1.81788175]
[1.0041531  1.00415322] [1.03248334 1.03248334] [1.00415427 1.00415387] [1.03248347 1.03248347]
[-1.78955113 -1.78955129] [1.8178814 1.8178814] [-1.7895528  -1.78955212] [1.81788181 1.81788181]
[2.57494937 2.57494933] [1.03248329 1.03248329] [2.5749512  2.57495063] [1.03248334 1.03248334]
[2.92283769 2.92283785] [1

In [187]:
for i in range(20):
    print(np.angle(vvrs[i])/np.angle(v1s[i]),np.angle(vvcs[i])/np.angle(v2s[i]))

[1.00000025 1.00000001] [1.00000009 1.00000009]
[1.00000006 1.00000012] [1.00000006 1.00000006]
[1.00000004 0.99999987] [1.00000002 1.00000002]
[0.99999988 0.99999984] [0.99999994 0.99999994]
[0.99999962 0.99999962] [1.00000007 1.00000007]
[0.99999925 0.99999903] [1.00000014 1.00000014]
[1.0000039  1.00000258] [1.00000016 1.00000016]
[1.00000117 1.00000065] [1.00000013 1.00000013]
[1.00000093 1.00000046] [1.00000023 1.00000023]
[1.00000071 1.0000005 ] [1.00000005 1.00000005]
[0.99999932 0.99999948] [1.00000014 1.00000014]
[0.99999895 0.99999914] [0.99999996 0.99999996]
[0.99999793 0.9999984 ] [1.0000002 1.0000002]
[0.99999506 0.99999555] [1.00000011 1.00000011]
[1.00001385 1.00001305] [1.00000023 1.00000023]
[1.00000305 1.00000311] [1.00000021 1.00000021]
[1.0000019  1.00000192] [1.0000003 1.0000003]
[1.00000143 1.00000153] [1.00000013 1.00000013]
[0.99999848 0.99999857] [1.00000031 1.00000031]
[0.99999779 0.99999786] [1.0000002 1.0000002]


In [188]:
for i in range(20):
    print(np.angle(vvrs[i])-np.angle(v1s[i]),np.angle(vvcs[i])-np.angle(v2s[i]))

[-4.38856061e-07 -1.97375130e-08] [1.59463299e-07 1.59463299e-07]
[1.52654020e-07 3.02385602e-07] [6.64319171e-08 6.64319171e-08]
[ 1.07809723e-07 -3.79139828e-07] [3.07801484e-08 3.07801484e-08]
[2.58355137e-07 3.41549400e-07] [-6.62145287e-08 -6.62145287e-08]
[-5.13348845e-07 -5.14855724e-07] [1.34320915e-07 1.34320915e-07]
[4.26073212e-07 5.48251763e-07] [1.41148736e-07 1.41148736e-07]
[-8.52754497e-07 -5.64774579e-07] [2.94390996e-07 2.94390996e-07]
[1.17369868e-06 6.51043247e-07] [1.29897217e-07 1.29897217e-07]
[-1.67118437e-06 -8.28188947e-07] [4.13822908e-07 4.13822908e-07]
[1.83325871e-06 1.29493014e-06] [4.86373348e-08 4.86373348e-08]
[-1.98605645e-06 -1.53260278e-06] [2.58018388e-07 2.58018388e-07]
[2.25092777e-06 1.84480473e-06] [-3.84066603e-08 -3.84066603e-08]
[-2.80046207e-06 -2.16148146e-06] [3.55889246e-07 3.55889246e-07]
[2.80058489e-06 2.52408356e-06] [1.141135e-07 1.141135e-07]
[-3.02917645e-06 -2.85452294e-06] [4.10603593e-07 4.10603593e-07]
[3.06342438e-06 3.121612