In [75]:
import numpy as np
import matplotlib.pyplot as plt
import holoviews as hv
import seaborn as sns
import pickle as pkl
from core import *

In [76]:
background_dir = "./Data/background_yarrays"
virus_dir = "./Data/yarrays"

In [90]:
with open(f"{background_dir}/background_all_y.pkl",'rb') as infile:
    background_yarrays = pkl.load(infile)
with open(f"{virus_dir}/virus_all_y.pkl",'rb') as infile:
    virus_yarrays = pkl.load(infile)

array([[[0.50000012-0.50000001j, 1.00000001-1.00000026j],
        [0.50000012-0.50000001j, 1.00000001-1.00000026j]],

       [[0.50000027+0.50000018j, 1.00000001+1.00000008j],
        [0.50000027+0.50000018j, 1.00000001+1.00000008j]],

       [[0.50000024-0.4999999j , 1.00000001-1.00000012j],
        [0.50000024-0.4999999j , 1.00000001-1.00000012j]],

       [[0.50000022+0.49999976j, 0.99999977+1.00000019j],
        [0.50000022+0.49999976j, 0.99999977+1.00000019j]],

       [[0.50000011-0.49999971j, 0.99999955-1.00000006j],
        [0.50000011-0.49999971j, 0.99999955-1.00000006j]],

       [[0.50000033+0.49999986j, 0.99999946+1.0000001j ],
        [0.50000033+0.49999986j, 0.99999946+1.0000001j ]],

       [[0.50000025-0.49999992j, 0.9999992 -1.00000006j],
        [0.50000025-0.49999992j, 0.9999992 -1.00000006j]],

       [[0.50000001+0.49999991j, 0.9999991 +0.99999994j],
        [0.50000001+0.49999991j, 0.9999991 +0.99999994j]],

       [[0.50000013-0.50000005j, 0.99999888-0.99999999j]

In [78]:
y0 = np.array([[complex(0.5,0.5),complex(1,1)],[complex(0.5,0.5),complex(1,1)]])

all_y = np.zeros((10,20,2,2),dtype="complex128")

for i in range(10):

    def Y(y,t):
        seq = DNA(5)
        alg = Sequence(seq).run()
        y_t = matrix_multiply(y,expm(alg))
        return y_t

    y_array = np.zeros((20,2,2),dtype="complex128")
    y = y0
    for n in range(20):
        y = rkmk_step(Y,y,n)
        y_array[n] = y

    all_y[i-1] = y_array

In [79]:
def matrix_vector_multiply(m,v,vector_type="row"):
    if vector_type == "row":
        return np.array([np.vdot(v,i) for i in m.T])
    elif vector_type == "column":
        return np.array([np.vdot(i,v) for i in m])

def vector_multiply(v1,v2):
    return np.vdot(v1,v2)

In [80]:
def random_complex_vector(n_components=2):
    vals = np.random.rand(n_components,2)
    vector = np.zeros(n_components,dtype="complex128")
    for i in range(n_components):
        vector[i] = complex(vals[i,0],vals[i,1])
    return vector

In [81]:
random_complex_vector()

array([0.86790372+0.92062319j, 0.67220254+0.3856258j ])

In [82]:
all_y[0].shape

(20, 2, 2)

In [192]:
v1 = random_complex_vector()
v2 = v1
vvr = v1
vvc = v1
v1s = []
v2s = []
vvrs = []
vvcs = []
v1

array([0.93306739+0.34077679j, 0.16525882+0.55710405j])

In [193]:
for i in all_y[1]:
    v1 = matrix_vector_multiply(i,v1,"row")
    v1s.append(v1)
    print(v1)

[0.10022271-0.99810346j 0.20044567-1.99620726j]
[-1.34682125+1.64748914j -2.69364245+3.29497931j]
[-4.49146505-0.45100095j -8.98293225-0.90200494j]
[ -7.41369701 -6.06069675j -14.82740306-12.12139022j]
[-2.02949817+20.2115847j  -4.05901325+40.42319092j]
[27.27313867-33.36160786j 54.54625973-66.72329392j]
[ 90.9520945  +9.13269132j 181.90430117+18.26550896j]
[150.12709622+122.72911201j 300.25459537+245.45818925j]
[41.09690433-409.2841453j  82.19444254-818.56903179j]
[ -552.28088291 +675.57114236j -1104.5618127 +1351.14472776j]
[-1841.77771116-184.93501589j -3683.55884888-369.87371962j]
[-3040.06788684-2485.26291877j -6080.14685439-4970.52764948j]
[ -832.20659717 +8287.99403074j -1664.42630225+16576.00833703j]
[11183.67955098-13680.2950763j  22367.37361854-27360.64332997j]
[37295.94379102+3744.9183159j  74592.01315607+7489.89626685j]
[ 61561.27253351 +50326.52905771j 123122.82309818+100653.16405972j]
[16852.11214009-167831.66635904j 33704.47656611-335663.92699554j]
[-226469.3791841 +2770

In [194]:
for i in all_y[0]:
    v2 = matrix_vector_multiply(i,v2,"column")
    v2s.append(v2)
    print(v2)

[-0.09569991+1.35928487j -0.09569991+1.35928487j]
[1.89537739+2.18247724j 1.89537739+2.18247724j]
[-0.4306495+6.11678225j -0.4306495+6.11678225j]
[8.52919901+9.82114925j 8.52919901+9.82114925j]
[-1.93792156+27.52552544j -1.93792156+27.52552544j]
[38.38140769+44.19517614j 38.38140769+44.19517614j]
[-8.72063964+123.86488683j -8.72063964+123.86488683j]
[172.71636099+198.87829795j 172.71636099+198.87829795j]
[-39.24285049+557.39202244j -39.24285049+557.39202244j]
[777.22369843+894.9523414j 777.22369843+894.9523414j]
[-176.59294831+2508.26371189j -176.59294831+2508.26371189j]
[3497.5061105+4027.28487853j 3497.5061105+4027.28487853j]
[-794.6672268+11287.18610481j -794.6672268+11287.18610481j]
[15738.77685214+18122.77737819j 15738.77685214+18122.77737819j]
[-3575.99345327+50792.32466978j -3575.99345327+50792.32466978j]
[70824.47980242+81552.47538586j 70824.47980242+81552.47538586j]
[-16091.95623428+228565.41521638j -16091.95623428+228565.41521638j]
[318710.11897294+366986.10312166j 318710.118

In [195]:
for i in virus_yarrays[2]:
    vvc = matrix_vector_multiply(i,vvc,"column")
    vvcs.append(vvc)
    print(vvc)

[-0.09570018+1.35928514j -0.09570018+1.35928514j]
[1.89537765+2.18247796j 1.89537765+2.18247796j]
[-0.43064994+6.11678312j -0.43064994+6.11678312j]
[8.52919883+9.82114832j 8.52919883+9.82114832j]
[-1.93792526+27.52551346j -1.93792526+27.52551346j]
[38.38136773+44.19514542j 38.38136773+44.19514542j]
[-8.72066991+123.86474285j -8.72066991+123.86474285j]
[172.71609206+198.87805258j 172.71609206+198.87805258j]
[-39.24303556+557.39111875j -39.24303556+557.39111875j]
[777.22226322+894.95083123j 777.22226322+894.95083123j]
[-176.59338118+2508.25954264j -176.59338118+2508.25954264j]
[3497.50062612+4027.27849631j 3497.50062612+4027.27849631j]
[-794.67054306+11287.17101032j -794.67054306+11287.17101032j]
[15738.75788644+18122.76082099j 15738.75788644+18122.76082099j]
[-3576.01332963+50792.28742923j -3576.01332963+50792.28742923j]
[70824.44302277+81552.47442941j 70824.44302277+81552.47442941j]
[-16092.08994813+228565.43140228j -16092.08994813+228565.43140228j]
[318710.1769067+366986.28900065j 318

In [196]:
for i in virus_yarrays[2]:
    vvr = matrix_vector_multiply(i,vvr,"row")
    vvrs.append(vvr)
    print(vvr)

[0.10022231-0.99810361j 0.20044538-1.99620716j]
[-1.346822 +1.64748946j -2.6936431+3.29497818j]
[-4.49146682-0.45100234j -8.98293144-0.90200252j]
[ -7.41370028 -6.0606971j -14.82740158-12.121391j ]
[-2.02950422+20.21158635j -4.05901144+40.42318315j]
[27.27310098-33.36162423j 54.54624845-66.72327458j]
[ 90.95207887 +9.13275907j 181.90423625+18.26554757j]
[150.12715099+122.72897008j 300.25463361+245.45800871j]
[41.09712426-409.28422332j 82.19484139-818.56874351j]
[ -552.28061869 +675.5716561j  -1104.56121502+1351.14486822j]
[-1841.77862836-184.93613847j -3683.55889125-369.87470864j]
[-3040.0706413 -2485.26483343j -6080.15003642-4970.52828883j]
[ -832.20600399 +8288.00565608j -1664.42806512+16576.02150739j]
[11183.70304977-13680.32054661j 22367.40255304-27360.66844363j]
[37296.03617734+3744.92633163j 74592.12944467+7489.88282585j]
[ 61561.47204606 +50326.68271059j 123123.04363445+100653.42081435j]
[16852.14392175-167832.30253215j 33704.40175183-335664.76251059j]
[-226470.28959456+277026.6

In [197]:
for i in range(20):
    print(np.abs(v1s[i]),np.abs(v2s[i]), np.abs(vvrs[i]), np.abs(vvcs[i]))

[1.00312268 2.00624572] [1.36264957 1.36264957] [1.00312278 2.00624559] [1.36264985 1.36264985]
[2.12794453 4.25588984] [2.89061626 2.89061626] [2.12794525 4.25588937] [2.89061697 2.89061697]
[4.51405141 9.02810527] [6.13192335 6.13192335] [4.51405331 9.02810422] [6.13192425 6.13192425]
[ 9.57574793 19.15150078] [13.00777492 13.00777492] [ 9.57575069 19.15150013] [13.0077741 13.0077741]
[20.31322276 40.62646862] [27.59366033 27.59366033] [20.31322501 40.62646071] [27.59364865 27.59364865]
[43.09084557 86.18174054] [58.53499851 58.53499851] [43.09083438 86.18171842] [58.53494911 58.53494911]
[ 91.40946091 182.81904606] [124.17149328 124.17149328] [ 91.40945213 182.81898533] [124.17135179 124.17135179]
[193.90868974 387.81766942] [263.40751461 263.40751461] [193.9086423  387.81758475] [263.407153 263.407153]
[411.34227492 822.68535066] [558.77174946 558.77174946] [411.34237453 822.68510367] [558.770861 558.770861]
[ 872.58841501 1745.17875114] [1185.33386469 1185.33386469] [ 872.58864552

In [198]:
for i in range(20):
    print(np.abs(vvrs[i])/np.abs(v1s[i]),np.abs(vvcs[i])/np.abs(v2s[i]))

[1.0000001  0.99999994] [1.00000021 1.00000021]
[1.00000034 0.99999989] [1.00000025 1.00000025]
[1.00000042 0.99999988] [1.00000015 1.00000015]
[1.00000029 0.99999997] [0.99999994 0.99999994]
[1.00000011 0.99999981] [0.99999958 0.99999958]
[0.99999974 0.99999974] [0.99999916 0.99999916]
[0.9999999  0.99999967] [0.99999886 0.99999886]
[0.99999976 0.99999978] [0.99999863 0.99999863]
[1.00000024 0.9999997 ] [0.99999841 0.99999841]
[1.00000026 0.99999985] [0.99999824 0.99999824]
[1.00000055 1.00000004] [0.99999836 0.99999836]
[1.00000085 1.00000037] [0.99999842 0.99999842]
[1.00000138 1.0000008 ] [0.99999869 0.99999869]
[1.00000196 1.00000107] [0.99999896 0.99999896]
[1.00000247 1.00000153] [0.9999993 0.9999993]
[1.00000317 1.0000021 ] [0.99999977 0.99999977]
[1.00000377 1.00000244] [1.00000011 1.00000011]
[1.00000379 1.000003  ] [1.00000037 1.00000037]
[1.00000444 1.00000327] [1.0000008 1.0000008]
[1.00000436 1.00000365] [1.00000099 1.00000099]


In [199]:
for i in range(20):
    print(np.abs(vvrs[i])-np.abs(v1s[i]),np.abs(vvcs[i])-np.abs(v2s[i]))

[ 1.02127412e-07 -1.28419777e-07] [2.84225091e-07 2.84225091e-07]
[ 7.22860078e-07 -4.67009292e-07] [7.11216606e-07 7.11216606e-07]
[ 1.89856362e-06 -1.04259995e-06] [9.0043059e-07 9.0043059e-07]
[ 2.75387943e-06 -6.51990362e-07] [-8.18406143e-07 -8.18406143e-07]
[ 2.24591234e-06 -7.90848792e-06] [-1.16816117e-05 -1.16816117e-05]
[-1.11909946e-05 -2.21139449e-05] [-4.93975952e-05 -4.93975952e-05]
[-8.77644031e-06 -6.07342020e-05] [-0.0001415 -0.0001415]
[-4.74343734e-05 -8.46626813e-05] [-0.00036161 -0.00036161]
[ 9.96087917e-05 -2.46992762e-04] [-0.00088846 -0.00088846]
[ 0.00023051 -0.00026954] [-0.00208128 -0.00208128]
[0.00102476 0.00014097] [-0.00412855 -0.00412855]
[0.00334438 0.00286824] [-0.00841482 -0.00841482]
[0.01150792 0.01328059] [-0.01482432 -0.01482432]
[0.03459242 0.03775667] [-0.02493685 -0.02493685]
[0.09272491 0.11436388] [-0.03575267 -0.03575267]
[0.251716   0.33324832] [-0.02483856 -0.02483856]
[0.63616536 0.82386003] [0.02553674 0.02553674]
[1.35603501 2.14368375

In [200]:
for i in range(20):
    print(np.angle(v1s[i]),np.angle(v2s[i]), np.angle(vvrs[i]), np.angle(vvcs[i]))

[-1.47071864 -1.47071853] [1.64108494 1.64108494] [-1.47071905 -1.47071867] [1.64108513 1.64108513]
[2.25611688 2.25611672] [0.85568681 0.85568681] [2.25611705 2.256117  ] [0.85568691 0.85568691]
[-3.04151522 -3.04151491] [1.64108493 1.64108493] [-3.04151496 -3.04151517] [1.64108499 1.64108499]
[-2.45627174 -2.45627217] [0.85568685 0.85568685] [-2.45627193 -2.45627209] [0.85568682 0.85568682]
[1.6708735  1.67087386] [1.64108487 1.64108487] [1.67087379 1.67087383] [1.64108503 1.64108503]
[-0.88547493 -0.88547567] [0.85568675 0.85568675] [-0.88547585 -0.88547562] [0.85568692 0.85568692]
[0.10007666 0.10007729] [1.6410848 1.6410848] [0.10007742 0.10007753] [1.64108512 1.64108512]
[0.6853218  0.68532107] [0.85568668 0.85568668] [0.68532105 0.68532065] [0.85568684 0.85568684]
[-1.4707201  -1.47071942] [1.64108474 1.64108474] [-1.47071958 -1.4707189 ] [1.64108519 1.64108519]
[2.25611859 2.25611773] [0.85568664 0.85568664] [2.25611799 2.25611741] [0.85568672 0.85568672]
[-3.04151694 -3.041516

In [201]:
for i in range(20):
    print(np.angle(vvrs[i])/np.angle(v1s[i]),np.angle(vvcs[i])/np.angle(v2s[i]))

[1.00000028 1.0000001 ] [1.00000012 1.00000012]
[1.00000008 1.00000013] [1.00000011 1.00000011]
[0.99999991 1.00000008] [1.00000004 1.00000004]
[1.00000008 0.99999997] [0.99999996 0.99999996]
[1.00000017 0.99999998] [1.0000001 1.0000001]
[1.00000104 0.99999995] [1.0000002 1.0000002]
[1.00000754 1.00000245] [1.0000002 1.0000002]
[0.99999891 0.99999938] [1.00000019 1.00000019]
[0.99999965 0.99999965] [1.00000027 1.00000027]
[0.99999973 0.99999986] [1.00000009 1.00000009]
[0.99999982 0.99999991] [1.00000018 1.00000018]
[1.00000003 1.00000008] [0.99999999 0.99999999]
[0.99999987 1.00000002] [1.00000024 1.00000024]
[0.99999987 0.99999979] [1.00000017 1.00000017]
[0.99999967 0.99999667] [1.00000027 1.00000027]
[0.99999987 1.00000054] [1.00000029 1.00000029]
[1.00000013 1.00000032] [1.00000035 1.00000035]
[1.00000008 1.00000027] [1.00000019 1.00000019]
[1.00000019 1.00000023] [1.00000036 1.00000036]
[0.99999975 0.9999997 ] [1.00000027 1.00000027]


In [202]:
for i in range(20):
    print(np.angle(vvrs[i])-np.angle(v1s[i]),np.angle(vvcs[i])-np.angle(v2s[i]))

[-4.08253517e-07 -1.42995338e-07] [1.8962127e-07 1.8962127e-07]
[1.75307792e-07 2.86072846e-07] [9.65898872e-08 9.65898872e-08]
[ 2.67044100e-07 -2.57696394e-07] [6.0938119e-08 6.0938119e-08]
[-1.87900155e-07  8.06347313e-08] [-3.60565582e-08 -3.60565582e-08]
[ 2.88308567e-07 -2.52153769e-08] [1.64478886e-07 1.64478886e-07]
[-9.17640731e-07  4.07420557e-08] [1.71306707e-07 1.71306707e-07]
[7.54531299e-07 2.45603749e-07] [3.24548967e-07 3.24548967e-07]
[-7.4544891e-07 -4.2283438e-07] [1.60055188e-07 1.60055188e-07]
[5.13027287e-07 5.17392529e-07] [4.43980879e-07 4.43980879e-07]
[-6.07068585e-07 -3.16090951e-07] [7.87953059e-08 7.87953059e-08]
[5.53923625e-07 2.64671899e-07] [2.8817636e-07 2.8817636e-07]
[-6.64694677e-08 -1.93418903e-07] [-8.24868929e-09 -8.24868929e-09]
[-2.10295148e-07  2.63043043e-08] [3.86047217e-07 3.86047217e-07]
[1.17282406e-07 1.84113174e-07] [1.44271471e-07 1.44271471e-07]
[-3.34695303e-08 -3.33372891e-07] [4.40761564e-07 4.40761564e-07]
[-9.20049592e-08  3.7226

In [203]:
for i in range(20):
    print(np.real(vvrs[i])/np.real(v1s[i]),np.real(vvcs[i])/np.real(v2s[i]))

[0.99999604 0.99999851] [1.0000029 1.0000029]
[1.00000055 1.00000024] [1.00000013 1.00000013]
[1.00000039 0.99999991] [1.00000101 1.00000101]
[1.00000044 0.9999999 ] [0.99999998 0.99999998]
[1.00000298 0.99999955] [1.00000191 1.00000191]
[0.99999862 0.99999979] [0.99999896 0.99999896]
[0.99999983 0.99999964] [1.00000347 1.00000347]
[1.00000036 1.00000013] [0.99999844 0.99999844]
[1.00000535 1.00000485] [1.00000472 1.00000472]
[0.99999952 0.99999946] [0.99999815 0.99999815]
[1.0000005  1.00000001] [1.00000245 1.00000245]
[1.00000091 1.00000052] [0.99999843 0.99999843]
[0.99999929 1.00000106] [1.00000417 1.00000417]
[1.0000021  1.00000129] [0.99999879 0.99999879]
[1.00000248 1.00000156] [1.00000556 1.00000556]
[1.00000324 1.00000179] [0.99999948 0.99999948]
[1.00000189 0.99999778] [1.00000831 1.00000831]
[1.00000402 1.00000375] [1.00000018 1.00000018]
[1.00000449 1.00000334] [1.00000914 1.00000914]
[1.00000386 1.00000304] [1.00000072 1.00000072]


In [204]:
for i in range(20):
    print(np.imag(vvrs[i])/np.imag(v1s[i]),np.imag(vvcs[i])/np.imag(v2s[i]))

[1.00000014 0.99999995] [1.0000002 1.0000002]
[1.0000002  0.99999966] [1.00000033 1.00000033]
[1.00000308 0.99999732] [1.00000014 1.00000014]
[1.00000006 1.00000006] [0.99999991 0.99999991]
[1.00000008 0.99999981] [0.99999957 0.99999957]
[1.00000049 0.99999971] [0.9999993 0.9999993]
[1.00000742 1.00000211] [0.99999884 0.99999884]
[0.99999884 0.99999926] [0.99999877 0.99999877]
[1.00000019 0.99999965] [0.99999838 0.99999838]
[1.00000076 1.0000001 ] [0.99999831 0.99999831]
[1.00000607 1.00000267] [0.99999834 0.99999834]
[1.00000077 1.00000013] [0.99999842 0.99999842]
[1.0000014  1.00000079] [0.99999866 0.99999866]
[1.00000186 1.00000092] [0.99999909 0.99999909]
[1.00000214 0.99999821] [0.99999927 0.99999927]
[1.00000305 1.00000255] [0.99999999 0.99999999]
[1.00000379 1.00000249] [1.00000007 1.00000007]
[1.00000364 1.00000249] [1.00000051 1.00000051]
[0.99999864 0.9999962 ] [1.00000076 1.00000076]
[1.00000511 1.00000456] [1.00000119 1.00000119]


In [314]:
def spinor(r,theta,phi,alpha):
    a = np.sqrt(r) * np.cos(theta/2) * np.exp(i*(-alpha-phi)/2)
    b = np.sqrt(r) * np.sin(theta/2) * np.exp(i*(-alpha+phi)/2)
    return np.array([a,b])
    
def random_vector():
    return np.random.rand(2)


def rotate_spinor(s,angle,axis):
    i = complex(0,1)
    sigmas = np.array([np.array([[0., 1.], [1., 0.]]),
        np.array([[0., -i], [i,  0.]]),
        np.array([[1., 0.], [0., -1.]])])
    I = np.array([[1., 0.], [0., 1.]])
    
    if axis == 'x':
        m = I * np.cos(angle/2.) + i * sigmas[0] * np.sin(angle/2.)
        return matrix_vector_multiply(m,s,"column")
    elif axis == 'y':
        m = I * np.cos(angle/2.) + i * sigmas[1] * np.sin(angle/2.)
        return matrix_vector_multiply(m,s,"column")
    elif axis == 'z':
        m = I * np.cos(angle/2.) + i * sigmas[2] * np.sin(angle/2.)
        return matrix_vector_multiply(m,s,"column")

unit_vectors = {'x': np.array([1,0,0]), 'y': np.array([0,1,0]), 'z': np.array([0,0,1])}

In [311]:
s = random_complex_vector()
s

array([0.21837762+0.87592761j, 0.56055916+0.23574689j])

In [313]:
rotate_spinor(s,2*np.pi,'x')

array([-0.21837762-0.87592761j, -0.56055916-0.23574689j])